version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:
  node-app:
    container_name: node-app
    restart: unless-stopped
    expose:
      - 3333
    ports:
      - "3333:3333"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      org.label-schema.group: "monitoring"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - monitor-net
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug